[package]
name = "dioxus-use-mounted"
description = "Dioxus hook to use a mounted elemented"
version = "0.3.0-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = "0.6.0-alpha.1"

[dev-dependencies]
dioxus-web = "0.6.0-alpha.0"
