[package]
name = "dioxus-use-mounted"
description = "Material design UI for Dioxus"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = "0.5.0-alpha.2"
dioxus-web = "0.5.0-alpha.2"
dioxus-signals = "0.5.0-alpha.2"
