[package]
name = "dioxus-use-mounted"
description = "Material design UI for Dioxus"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
dioxus = "0.5.1"

[dev-dependencies]
dioxus-web = "0.5.1"
